# frozen_string_literal: true

# Gemfile

source 'https://rubygems.org'

ruby '>= 2.7.0'

gem 'httparty'
gem 'json'
gem 'rack'
gem 'rackup'
gem 'redis'
gem 'rmagick'
gem 'sidekiq'
gem 'sinatra'

group :test do
  gem 'rspec', '~> 3.10'
  gem 'webmock', '~> 3.13'
end

group :development, :test do
  gem 'byebug'
  gem 'dotenv', '~> 2.7'
end
